In [2]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Parameters
U = np.array([
    [-1.1106, -0.0596, -0.4091, -0.0648],
    [-0.6809, -0.6610, -1.2819,  1.0004],
    [ 0.0142,  0.3060, -0.2849, -0.8013]
])
V = np.array([
    [ 1.1086],
    [-0.4641],
    [ 0.6646],
    [-0.5301]
])
W = np.array([
    [ 0.0918, -0.9585,  0.8270, -0.2248],
    [ 0.2738, -0.3263, -0.1596, -1.3147],
    [-2.1335,  2.4787, -0.8577, -0.0218],
    [ 0.4040,  1.5391,  0.3984, -0.8801]
])
c = np.array([[0.8004]])
b = np.array([
    [ 0.0409],
    [ 0.1551],
    [-0.3211],
    [ 2.1458]
])
X = np.array([
    [-2.5092,  1.9732, -8.8383,  4.1615,  6.6489],
    [ 9.0143, -6.8796,  7.3235, -9.5883, -5.7532],
    [ 4.6399, -6.8801,  2.0223,  9.3982, -6.3635]
])
d = np.array([
    [ 1.1963,  2.0975,  0.3877,  1.0453, -1.3718]
])

# Forward Pass
h = np.zeros((W.shape[0], X.shape[1] + 1))
y = np.zeros((1, X.shape[1]))

for i in range(X.shape[1]):
    x_t = X[:, [i]]
    a_h = U.T @ x_t + W.T @ h[:, [i]] + b
    h[:, [i + 1]] = sigmoid(a_h)

    a_y = V.T @ h[:, [i + 1]] + c
    y[:, [i]] = sigmoid(a_y)

# Backward Pass
delta_y = (y - d) * (y * (1 - y))
delta_h = np.zeros((W.shape[0], X.shape[1]))

for i in reversed(range(X.shape[1])):
    term = V @ delta_y[:, [i]]

    if i < X.shape[1] - 1:
        term += W @ delta_h[:, [i + 1]]

    delta_h[:, [i]] = term * (h[:, [i + 1]] * (1 - h[:, [i + 1]]))

# Gradients
grad_V = h[:, 1:] @ delta_y.T
grad_U = np.zeros_like(U)
grad_W = np.zeros_like(W)

for i in range(X.shape[1]):
    x_t = X[:, [i]]
    h_prev = h[:, [i]]
    delta_h_t = delta_h[:, [i]]
    grad_U += x_t @ delta_h_t.T
    grad_W += h_prev @ delta_h_t.T


print("Output:")
print(y.round(4))
print("\nDelta y:")
print(delta_y.round(4))
print("\nDelta h:")
print(delta_h.round(4))
print("\nGradient V:")
print(grad_V.round(4))
print("\nGradient U:")
print(grad_U.round(4))
print("\nGradient W:")
print(grad_W.round(4))


Output:
[[0.5758 0.8613 0.7797 0.8843 0.6959]]

Delta y:
[[-0.1516 -0.1477  0.0673 -0.0165  0.4376]]

Delta h:
[[-0.0063 -0.0083  0.0026  0.0003  0.0024]
 [ 0.0006  0.0013 -0.0043  0.     -0.0103]
 [-0.     -0.      0.0001 -0.      0.0008]
 [ 0.      0.0179 -0.0001  0.     -0.0547]]

Gradient V:
[[-0.0935]
 [ 0.2617]
 [ 0.2723]
 [ 0.0179]]

Gradient U:
[[-0.0059 -0.0293  0.0048 -0.3279]
 [ 0.0021  0.0244 -0.0041  0.1914]
 [ 0.0203  0.0509 -0.005   0.2249]]

Gradient W:
[[ 0.0047 -0.0136  0.0008 -0.0503]
 [ 0.0049 -0.0145  0.0008 -0.0545]
 [ 0.005  -0.0146  0.0008 -0.0547]
 [-0.0068 -0.0006  0.      0.0179]]
